version: "3"
services:
  side-car:
    image: tarfeef101/s3_sidecar
    env_file: .env.aws
    environment:
      - FILES=db/db_schema.sql
    volumes:
      - sh-ltc-testnet-v0-10-0-alpha-3-side-car:/opt/
    ports:
      - 2049:2049
    networks:
      - bcn
  db:
    env_file: .env.aws
    volumes:
      - db-ltc-testnet-v0-10-0-alpha-3-data:/var/lib/postgresql/data
      - sh-ltc-testnet-v0-10-0-alpha-3-side-car:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        reservations:
          memory: 16Gb
        limits:
          memory: 16384M
          cpus: '2'
    depends_on:
      - side-car
  node:
    image: bcdb/litecoind:0.21
    networks:
      - bitcoin
    command:
      [
        "litecoind",
        "-testnet=1",
        "-dbcache=4000",
        "-txindex=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=19332",
        "-port=19335",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
    ports:
      - 19335:19335
      - 19332:19332
      - 28332:28332
    volumes:
      - bc-ltc-testnet-v0-10-0-alpha-3-data:/home/litecoin/.litecoin
    depends_on:
      - side-car
    deploy:
      resources:
        limits:
          memory: 16384M
          cpus: '2'
  bcn:
    image: bcdb/bcn:0.10.0-alpha.3
    platform: linux/amd64
    env_file: .env.aws
    environment:
      - BCN_ENV=prod
      - RPC_PORT=19332
      - RPC_HOST=node
      - ZMQ_URL=tcp://node:28332
      - CHAIN=LTC
      - NETWORK=testnet
      - DEBUG_MODE=5
      - BCN_URL=https://node.bitcoincomputer.io
    deploy:
      resources:
        reservations:
          memory: 16Gb
        limits:
          memory: 16384M
          cpus: '2'
  sync:
    command: npm run sync
    image: bcdb/bcn:0.10.0-alpha.3
    platform: linux/amd64
    env_file: .env.aws
    depends_on:
      - node
      - bcn
      - db
    deploy:
      resources:
        reservations:
          memory: 16Gb
        limits:
          memory: 16384M
          cpus: '2'
    environment:
      - BCN_ENV=prod
      - CHAIN=LTC
      - NETWORK=testnet
      - ZMQ_URL=tcp://node:28332
      - DEBUG_MODE=5
      - BCN_URL=https://node.bitcoincomputer.io
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - RPC_AUTH=${RPC_AUTH}
      - RPC_HOST=node
      - RPC_PORT=19332
      - DEFAULT_WALLET=${DEFAULT_WALLET}
    networks:
      - bitcoin
      - bcn

volumes:
  sh-ltc-testnet-v0-10-0-alpha-3-side-car: {}
  db-ltc-testnet-v0-10-0-alpha-3-data:
  bc-ltc-testnet-v0-10-0-alpha-3-data:

x-aws-loadbalancer: ltc-testnet-v0-10-0-alpha-3
x-aws-cloudformation:
  Resources:
    BcnTaskDefinition:
      Properties:
        runtimePlatform: {
          operatingSystemFamily: "LINUX",
          cpuArchitecture: "AMD64"
        }
    SyncTaskDefinition:
      Properties:
        runtimePlatform: {
          operatingSystemFamily: "LINUX",
          cpuArchitecture: "AMD64"
        }
    BcnService:
      Properties:
        HealthCheckGracePeriodSeconds: 2800000 #13 hs aprox
    SidecarService:
      Properties:
        HealthCheckGracePeriodSeconds: 2147483647 #69 years
    # Keep these lines that automatically defines properties for the load balancer
    # To be switched from the old cluster to the new-format-version cluster.
    # BcnTCP3000TargetGroup:
    #   Properties:
    #     Port: 3000
    #     Protocol: TCP
    #     Tags:
    #     - Key: com.docker.compose.project
    #       Value: ltc-testnet-cluster-v0.6.0
    #     TargetType: ip
    #     VpcId: vpc-00661fca497933772
    #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
    # BcnTCP80Listener:
    #   Properties:
    #     DefaultActions:
    #     - ForwardConfig:
    #         TargetGroups:
    #         - TargetGroupArn:
    #             Ref: BcnTCP3000TargetGroup
    #       Type: forward
    #     LoadBalancerArn: arn:aws:elasticloadbalancing:us-east-1:428034753515:loadbalancer/net/ltc-testnet-bc-node/a7868b3f0a5eb0df
    #     Port: 80
    #     Protocol: TCP
    #   Type: AWS::ElasticLoadBalancingV2::Listener
    # BcnTCP443Listener:
    #   Properties:
    #     DefaultActions:
    #     - ForwardConfig:
    #         TargetGroups:
    #         - TargetGroupArn:
    #             Ref: BcnTCP3000TargetGroup
    #       Type: forward
    #     LoadBalancerArn: arn:aws:elasticloadbalancing:us-east-1:428034753515:loadbalancer/net/ltc-testnet-bc-node/a7868b3f0a5eb0df
    #     Certificates:
    #     - CertificateArn: arn:aws:acm:us-east-1:428034753515:certificate/cdee9e26-6ed7-4d40-a6b2-37dc86b3e60d
    #     Port: 443
    #     Protocol: TLS
    #     SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
    #   Type: AWS::ElasticLoadBalancingV2::Listener