version: "3"
services:
  db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    networks:
      - bcn
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  bcn:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${PORT}/health/ || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=bcn-admin
      - RPC_PASSWORD=kH4nU5Okm6-uyC0_mA5ztVNacJqZbYd_KGLl6mx722A=
    depends_on:
      - db
    working_dir: /src
    networks:
      - bitcoin
      - bcn
networks:
  bitcoin: null
  bcn: null
