services:
  db:
    env_file: .env
    volumes:
      - ./chain-setup/pepe-regtest/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    restart: always
  node:
    env_file: .env
    networks:
      - bitcoin
    image: pepeenthusiast/pepecoin-core:1.0.1
    ports:
      - 18444:18444
      - 18332:18332
      - 28332:28332
    volumes:
      - ./chain-setup/pepe-regtest/blockchain-data:/home/pepecoin/.pepecoin
    restart: always
    command:
      [
        "pepecoind",
        "-regtest=1",
        "-dbcache=4000",
        "-txindex=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=18332",
        "-port=18444",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
  bcn:
    image: bitcoin-computer-node
    env_file: .env
    depends_on:
      - db
      - node
    environment:
      - BCN_ENV=dev
      - RPC_HOST=node
      - RPC_PORT=18332
      - ZMQ_URL=tcp://node:28332
      - NETWORK=regtest
      - CHAIN=PEPE
      - BCN_URL=http://127.0.0.1:1031
    restart: always

