version: "3"
services:
  db:
    env_file: .env
    volumes:
      - ./chain-setup/ltc-testnet/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
  node:
    image: bcdb/litecoind:0.21
    networks:
      - bitcoin
    command:
      [
        "litecoind",
        "-testnet=1",
        "-dbcache=4000",
        "-txindex=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=19332",
        "-port=19335",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
    ports:
      - 19335:19335
      - 19332:19332
      - 28332:28332
    volumes:
      - ./chain-setup/ltc-testnet/blockchain-data:/home/litecoin/.litecoin
  bcn:
    image: bcdb/bcn:0.9.12
    # image: bitcoin-computer-node
    # build: .
    env_file: .env
    environment:
      - BCN_ENV=prod
      - RPC_HOST=node
      - RPC_PORT=19332
      - ZMQ_URL=tcp://node:28332
      - NETWORK=testnet
      - CHAIN=LTC
      - BCN_URL=http://127.0.0.1:3000
    depends_on:
      - db
      - node
  sync:
    command: npm run sync
    image: bcdb/bcn:0.9.12
    # image: bitcoin-computer-node
    env_file: .env
    depends_on:
      - db
      - node
    environment:
      - BCN_ENV=prod
      - RPC_HOST=node
      - RPC_PORT=19332
      - NETWORK=testnet
      - CHAIN=LTC
      - ZMQ_URL=tcp://node:28332
      - BCN_URL=http://127.0.0.1:3000
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
    networks:
      - bitcoin
      - bcn
